name: Delete all files in workspace
on: [push]
jobs:
  delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Delete all files in workspace
        run: rm -rf ${{ github.workspace }}/*